apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: staging
spec:
  destination:
    name: ''
    namespace: staging
    server: 'https://kubernetes.default.svc'
  source:
    path: project/helm
    repoURL: 'https://github.com/akbarpunjwani/nd064_course_1'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-staging.yaml
  project: default
  syncPolicy:
    automated: null