apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: project/helm
    repoURL: 'https://github.com/akbarpunjwani/nd064_course_1'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-prod.yaml
  project: techtrends
  syncPolicy:
    automated: null